volumes:
  pg_data:
  static:
  media:

services:
  db:
    image: postgres:latest
    restart: unless-stopped
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
  redis:
    image: redis:latest
    restart: unless-stopped
    ports:
      - 6379:6379
  crowdfunding:
    image: meteopavel/crowdfunding_api-crowdfunding
    restart: unless-stopped
    command: >
      sh -c "python manage.py collectstatic --noinput &&
             python manage.py makemigrations &&
             python manage.py migrate &&
             uvicorn crowdfunding.asgi:application --host 0.0.0.0 --port 8000"
    env_file: .env
    volumes: 
      - static:/static
      - media:/app/media 
    depends_on:
      - db
      - redis
  celery:
    image: meteopavel/crowdfunding_api-celery
    restart: unless-stopped
    command: celery -A crowdfunding worker --loglevel=info
    env_file: .env
    depends_on:
      - redis
  gateway:
    image: meteopavel/crowdfunding_api-gateway
    restart: unless-stopped
    env_file: .env 
    ports:
      - 8333:80 
    volumes: 
      - static:/static
      - media:/media
    depends_on:
      - crowdfunding