volumes:
  pg_data:
  static:
  media:

services:
  db:
    image: postgres:latest
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
  crowdfunding:
    build: ./crowdfunding/
    command: >
      sh -c "python manage.py collectstatic --noinput &&
             python manage.py makemigrations &&
             python manage.py migrate &&
             uvicorn crowdfunding.asgi:application --host 0.0.0.0 --port 8000"
    env_file: .env
    volumes: 
      - static:/static
      - media:/app/media 
    depends_on:
      - db
      - redis
  celery:
    build: ./crowdfunding/
    command: celery -A crowdfunding worker --loglevel=info
    env_file: .env
    depends_on:
      - redis
  gateway:
    build: ./gateway/
    env_file: .env 
    ports:
      - 8000:80 
    volumes: 
      - static:/static
      - media:/media
    depends_on:
      - crowdfunding